### ISSUE TITLE
Does not work with Docker OS X beta

### ISSUE THREAD

**Issue by fuel-wlightning** [gregarcara/concourse-docker#4]
Looks like lack of btrfs causes concourse worker to fail.

concourse-worker_1  | {"timestamp":"1462815965.824848652","source":"worker","message":"worker.baggageclaim.fs.run-command.failed","log_level":2,"data":{"args":["bash","-e","-x","-c","\n\t\tif [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_PATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! file $IMAGE_PATH | grep BTRFS; then\n\t\t\tmkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mountpoint -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"],"command":"/bin/bash","env":["PATH=/opt/concourse/worker/linux/btrfs:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","MOUNT_PATH=/opt/concourse/worker/volumes","IMAGE_PATH=/opt/concourse/worker/volumes.img","SIZE_IN_BYTES=63371726848"],"error":"exit status 32","session":"2.1.1","stderr":"+ '[' '!' -e /opt/concourse/worker/volumes.img ']'\n+ touch /opt/concourse/worker/volumes.img\n+ truncate -s 63371726848 /opt/concourse/worker/volumes.img\n++ losetup -j /opt/concourse/worker/volumes.img\n++ cut -d: -f1\n+ lo=\n+ '[' -z '' ']'\n++ losetup -f --show /opt/concourse/worker/volumes.img\n+ lo=/dev/loop3\n+ file /opt/concourse/worker/volumes.img\nbash: line 11: file: command not found\n+ grep BTRFS\n+ mkfs.btrfs --nodiscard /opt/concourse/worker/volumes.img\n+ mkdir -p /opt/concourse/worker/volumes\n+ mountpoint -q /opt/concourse/worker/volumes\n+ mount -t btrfs /dev/loop3 /opt/concourse/worker/volumes\nmount: unknown filesystem type 'btrfs'\n","stdout":"btrfs-progs v4.4\nSee http://btrfs.wiki.kernel.org for more information.\n\nLabel:              (null)\nUUID:               200b5ea1-86c4-4a6e-9b55-50b5b76e99a4\nNode size:          16384\nSector size:        4096\nFilesystem size:    59.02GiB\nBlock group profiles:\n  Data:             single            8.00MiB\n  Metadata:         DUP               1.01GiB\n  System:           DUP              12.00MiB\nSSD detected:       no\nIncompat features:  extref, skinny-metadata\nNumber of devices:  1\nDevices:\n   ID        SIZE  PATH\n    1    59.02GiB  /opt/concourse/worker/volumes.img\n\n"}}

**Comment by gregarcara** [comment]
I've been using this on my work laptop w/ Docker beta with no issues. I'll take a look tomorrow.

**Comment by gregarcara** [comment]
I updated the Dockerfile to use a newer concourse binary that uses guardian (runc). It works on my macbook pro with docker beta. Please verify it's working for you and then close this issue.

**Comment by fuel-wlightning** [comment]
Hmm.. still fails at same spot. Concourse is now reported version v0.76.0... is that the new RC?

(below is the log entry prettified)

```
{
   "timestamp":"1463158129.200583458",
   "source":"worker",
   "message":"worker.baggageclaim.fs.run-command.failed",
   "log_level":2,
   "data":{
      "args":[
         "bash",
         "-e",
         "-x",
         "-c",
         "\n\t\tif [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_PATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! file $IMAGE_PATH | grep BTRFS; then\n\t\t\tmkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mountpoint -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"
      ],
      "command":"/bin/bash",
      "env":[
         "PATH=/opt/concourse/worker/linux/btrfs:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
         "MOUNT_PATH=/opt/concourse/worker/volumes",
         "IMAGE_PATH=/opt/concourse/worker/volumes.img",
         "SIZE_IN_BYTES=63371726848"
      ],
      "error":"exit status 32",
      "session":"2.1.1",
      "stderr":"+ '[' '!' -e /opt/concourse/worker/volumes.img ']'\n+ touch /opt/concourse/worker/volumes.img\n+ truncate -s 63371726848 /opt/concourse/worker/volumes.img\n++ losetup -j /opt/concourse/worker/volumes.img\n++ cut -d: -f1\n+ lo=\n+ '[' -z '' ']'\n++ losetup -f --show /opt/concourse/worker/volumes.img\n+ lo=/dev/loop0\n+ file /opt/concourse/worker/volumes.img\nbash: line 11: file: command not found\n+ grep BTRFS\n+ mkfs.btrfs --nodiscard /opt/concourse/worker/volumes.img\n+ mkdir -p /opt/concourse/worker/volumes\n+ mountpoint -q /opt/concourse/worker/volumes\n+ mount -t btrfs /dev/loop0 /opt/concourse/worker/volumes\nmount: unknown filesystem type 'btrfs'\n",
      "stdout":"btrfs-progs v4.4\nSee http://btrfs.wiki.kernel.org for more information.\n\nLabel:              (null)\nUUID:               f524f0a6-6c33-4bfb-a47a-4b537faccb93\nNode size:          16384\nSector size:        4096\nFilesystem size:    59.02GiB\nBlock group profiles:\n  Data:             single            8.00MiB\n  Metadata:         DUP               1.01GiB\n  System:           DUP              12.00MiB\nSSD detected:       no\nIncompat features:  extref, skinny-metadata\nNumber of devices:  1\nDevices:\n   ID        SIZE  PATH\n    1    59.02GiB  /opt/concourse/worker/volumes.img\n\n"
   }
}
```

**Comment by gregarcara** [comment]
Issue resolved after updating the docker hub images and not using the image: property and instead using  image_resource https://concourse.ci/running-tasks.html#image_resource
